/**
 * Build Script for AI Color Theme Picker
 *
 * Concatenates all JS source files from src/ into dist/popup.js
 * in the correct dependency order.
 *
 * Usage: node build.js
 *
 * The output is deterministic: the same sources always produce a byte-identical
 * bundle. That is what lets `npm run check:dist` catch a dist/ that was not
 * rebuilt after a src/ change — a real hazard here, because popup.html loads
 * dist/popup.js, so editing src/ alone changes nothing at runtime.
 */

const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, 'src');
const DIST_DIR = path.join(__dirname, 'dist');
const OUTPUT_FILE = path.join(DIST_DIR, 'popup.js');

// Files in dependency order
const JS_FILES = [
    'shared/icons.js',
    'shared/color.js',
    'shared/utils.js',
    'popup/state.js',
    'popup/storage.js',
    'popup/ui.js',
    'popup/api-keys.js',
    'popup/generator.js',
    'popup/init.js',
];

const buildBundle = () => {
    let output = '// Auto-generated by build.js — do not edit directly\n';
    output += '// Run `node build.js` after any change under src/\n\n';

    for (const file of JS_FILES) {
        const filePath = path.join(SRC_DIR, file);

        if (!fs.existsSync(filePath)) {
            throw new Error(`Missing file: ${filePath}`);
        }

        const content = fs.readFileSync(filePath, 'utf-8');
        output += `// ─── ${file} ${'─'.repeat(Math.max(0, 60 - file.length))} \n`;
        output += content;
        output += '\n\n';
    }

    return output;
};

const writeBundle = () => {
    if (!fs.existsSync(DIST_DIR)) {
        fs.mkdirSync(DIST_DIR, { recursive: true });
    }

    const output = buildBundle();
    fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');

    console.log('\n✅ Build complete: dist/popup.js');
    console.log(`   Size: ${(Buffer.byteLength(output) / 1024).toFixed(1)} KB`);
    console.log(`   Files: ${JS_FILES.length} source files concatenated\n`);
};

module.exports = { JS_FILES, OUTPUT_FILE, buildBundle };

if (require.main === module) {
    try {
        writeBundle();
    } catch (err) {
        console.error(`ERROR: ${err.message}`);
        process.exit(1);
    }
}
